/// A lightweight companion package for Flutter modular localization.
///
/// This package provides runtime utilities for the Modular Flutter L10n system.
/// Use it in conjunction with the Modular Flutter L10n VS Code extension.
///
/// ## Features
///
/// - **RTL Support**: Built-in detection for Arabic, Hebrew, Urdu, and other RTL languages
/// - **Locale Utilities**: Parse, match, and get display names for locales
/// - **Zero Performance Impact**: All utilities are static with no state management overhead
/// - **Cross-Platform**: Works on Android, iOS, Web, macOS, Windows, and Linux
///
/// ## Important Note
///
/// This package does NOT handle locale switching or state management.
/// It only provides information about locales. Handle locale switching
/// using your preferred state management solution (Provider, Riverpod, Bloc, etc.).
///
/// ## Quick Start
///
/// ### Check RTL Support
///
/// ```dart
/// import 'package:modular_l10n/modular_l10n.dart';
///
/// // Check if locale is RTL
/// if (LocaleUtils.isRtl(const Locale('ar'))) {
///   // Handle RTL layout
/// }
///
/// // Or use the extension
/// if (locale.isRtl) {
///   // Handle RTL layout
/// }
/// ```
///
/// ### Get Text Direction
///
/// ```dart
/// // Get text direction for a locale
/// TextDirection direction = LocaleUtils.getTextDirection(locale);
///
/// // Use in widgets
/// Directionality(
///   textDirection: locale.textDirection,
///   child: child,
/// )
/// ```
///
/// ### Parse Locale Strings
///
/// ```dart
/// // Parse various locale formats
/// Locale locale1 = LocaleUtils.parseLocale('en_US');
/// Locale locale2 = LocaleUtils.parseLocale('zh_Hans_CN');
/// ```
///
/// ### Get Display Names
///
/// ```dart
/// // Get English name
/// String englishName = locale.displayName; // "Arabic"
///
/// // Get native name
/// String nativeName = locale.nativeName; // "العربية"
/// ```
///
/// ### Find Best Locale Match
///
/// ```dart
/// final supportedLocales = ML.supportedLocales;
/// final deviceLocale = WidgetsBinding.instance.window.locale;
///
/// Locale? bestMatch = LocaleUtils.findBestMatch(
///   deviceLocale,
///   supportedLocales,
/// );
/// ```
///
/// ## Integration with Generated Code
///
/// This package works seamlessly with code generated by the
/// Modular Flutter L10n VS Code extension:
///
/// ```dart
/// // In your MaterialApp
/// MaterialApp(
///   locale: currentLocale, // From your state management
///   supportedLocales: ML.supportedLocales,
///   localizationsDelegates: [
///     ML.delegate,
///     GlobalMaterialLocalizations.delegate,
///     GlobalWidgetsLocalizations.delegate,
///     GlobalCupertinoLocalizations.delegate,
///   ],
///   builder: (context, child) {
///     // Use locale utilities
///     final textDirection = ML.current.locale.textDirection;
///     return Directionality(
///       textDirection: textDirection,
///       child: child!,
///     );
///   },
///   home: HomePage(),
/// )
/// ```
///
/// ## Example: Locale Switcher
///
/// ```dart
/// class LocaleSwitcher extends StatelessWidget {
///   final ValueChanged<Locale> onLocaleChanged;
///
///   const LocaleSwitcher({required this.onLocaleChanged});
///
///   @override
///   Widget build(BuildContext context) {
///     return DropdownButton<Locale>(
///       value: Localizations.localeOf(context),
///       items: ML.supportedLocales.map((locale) {
///         return DropdownMenuItem(
///           value: locale,
///           child: Row(
///             children: [
///               Text(locale.nativeName),
///               if (locale.isRtl) const Icon(Icons.format_textdirection_r_to_l),
///             ],
///           ),
///         );
///       }).toList(),
///       onChanged: (locale) {
///         if (locale != null) onLocaleChanged(locale);
///       },
///     );
///   }
/// }
/// ```
library modular_l10n;

export 'src/locale_utils.dart';
